### ISSUE TITLE
ReferenceErrors in domain error handler

### ISSUE THREAD

**Issue by danmactough** [amino/amino-gateway#4]
This block where we try to gracefully die refers to variables that don't exist:

https://github.com/amino/amino-gateway/blob/master/index.js#L23-L34
- no `server`
- no `res`

Looks like it's copy/pasted from the [docs](http://nodejs.org/api/domain.html#domain_warning_don_t_ignore_errors), but in the example there, those variables are in the outer scope.

Not sure we need to do anything other than `cluster.worker.disconnect()`.

Thoughts?

**Comment by carlos8f** [comment]
whoops, I guess it fails silently due to the try/catch.

just reminds me how hopeless the whole domain/error event thing has become. At first glance I would need to create a new domain for every request, I'm not really down with that though.

**Comment by carlos8f** [comment]
typos aside, in practice I don't think domains have ever worked how I intended them to work. I have had luck with the [trycatch](https://github.com/crabdude/trycatch) API but (at least back then) the module did horrible things and I didn't want to be an accomplice.

**Comment by danmactough** [comment]
> At first glance I would need to create a new domain for every request

Yeah, if the goal would be to serve a 500 error, that's true.

**Comment by carlos8f** [comment]
fixed by #6
